# fly.toml app configuration file generated for whisperplz on 2023-10-12T14:48:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = ""
primary_region = "ord"

[build]

[[mounts]]
  source = "data"
  destination = "/root/.cache"
